FROM node:18

WORKDIR /app

COPY frontend/ ./frontend/
WORKDIR /app/frontend

RUN npm install -g create-react-app && npm init -y && npm install
COPY frontend/package.json frontend/package-lock.json ./
RUN npm install

COPY frontend/. ./

RUN npm run build

EXPOSE 3000
CMD ["npx", "serve", "-s", "build"]
